name: Build and Deploy Site
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile ts 
        run: |
          rm .gitignore
          npm init -y
          npm install -i typescript --save-dev
          npx tsc

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: github-pages